### ISSUE TITLE
Conditions are totally broken

### ISSUE THREAD

**Issue by ghoseandco** [Desertsnowman/Caldera-Forms#228]
SOS
Hello.. In the new Stable version (1.3.0) for WP, the Conditions are totally broken. Please restore this as soon as possible.

* Show/Hide not working
* Required nature remain active even if the field is hidden
*No option to disable

**Comment by soumyabg** [comment]
I foun the AND operator is NOT working, that is the reason it is broken

**Comment by soumyabg** [comment]
Further, 
Conditions depending on Check box input shows erratic behaviour.
If Check box comes after the target Applied Fields, Conditions seems to work.

**Comment by soumyabg** [comment]
What happening here.. Now the "OR" operator is working. Is it some cache related issue?

**Comment by dlincoln** [comment]
I've noticed that previously-assigned conditions in older forms are not recalled properly when I go to edit them. Specifically the "type" is empty or not-set, even though it was set at some point. Now the odd (and very good!) thing is that the conditions actually work as they did when I last saved it, so the issue for me is mostly ui. This is the same behavior as the Pods processor (it won't recall previously assigned fields when you open/look, but it submits documents to them just fine).

New forms are hard to make though, so this is a fairly serious break in functionality.

**Comment by Shelob9** [comment]
Thanks for these reports and sorry about the issues. David's top task is to
sort issues with conditionals and push out a 1.3.0.1 release.

**Comment by soumyabg** [comment]
+1 for @dlincoln

**Comment by Desertsnowman** [comment]
Found there is a delay is some option settings so it was capturing the setting of the previous change. long story short- I fixed it and will be updated shortly.

**Comment by Desertsnowman** [comment]
@soumyabg I want to push this out asap. can you test the current-dev branch to see if the issues are resolved for you?

**Comment by Desertsnowman** [comment]
@dlincoln that is correct. this was just a UI issue. the new conditions are still the same as the old. It's just the new UI was rendering the > symbol differently so it wouldn't pick it up thereby ignoring and resetting to is. same with the "Disable" type. I left it out of the options. so it reset to show. but only if you tried to edit and saved the form. I have sorted it now.

**Comment by soumyabg** [comment]
Unfortunately I'm out of town for today @Desertsnowman 
I saw the code compare of current Dev branch
It looks 'near' perfect, if you have tested, lets propagate it

**Comment by soumyabg** [comment]
I somehow managed to test it @Desertsnowman 
NO, IT IS STILL BROKEN
Disable option is there, but if the applied field is required, then it will not work
And after this update, Hide is NOT working

**Comment by Desertsnowman** [comment]
what are the chances of you exporting the form for me to try?

**Comment by soumyabg** [comment]
This is the form that is working (in stable)
https://www.dropbox.com/s/jhyosaous8xg8k3/recommend-a-route-export.json?dl=0
Please import it in Dev, and change the "Start Date" condition ( "Date is fixed" in Conditions) to Type "Disable". 
In my system, this broke the logic, now you cannot go the next page as required field Start date (now diasbled) but still remain required.
Adding to this, there is another input below this, which "You are", where if "couple" or "solo" is NOT selected then number field of Adult and Toddler will be shown, this Dev version breaks that too.

You can see the active form on http://ontrip.in/http://ontrip.in/

**Comment by Desertsnowman** [comment]
wow, that helps alot! I'll get on it and let you know ASAP

**Comment by Shelob9** [comment]
@soumyabg I just tested this with the latest current-dev. I think David made one commit after you posted your last comment. 

The hide/show of the extra fields on couple/solo seem to work fine.

I do see that when the required Start Date is still required when disabled. I may be wrong, but disabled seems like the wrong conditional to use here. I would use hide instead. Normally disabled is used for disabling next/back/submit buttons so you can't use them unless a condition is met (example is an agree to terms checkbox).

Disabling a required field, I think should prevent the form form being submittable. If the field is not required in some situations, hide it.

**Comment by soumyabg** [comment]
@Shelob9 That's great! I will test. 
In previous stable version, Disable worked like "Hide" (just it was shown as an inactive field instead of completely disappearing), so I expected the same behaviour here. If the Disable type is only applicable to Button field, we should not show other types of field in the Applied Fields list on Conditions tab.

As a user-centric UI developer, I think Disable (and not required) works better than Hide (and not required). The User can see which fields get affected by her decision (ticking or filling up or selecting an option)

**Comment by dlincoln** [comment]
I think you really need both hide AND disable. I see what you're saying: a conditional field may exist to add a new value to a taxonomy dropdown. While a "add new entry" value with a little code would accomplish the same thing (unhiding and enabling a field), the user has to open the list to know this is possible. That could be confusing, and imply the user needs to go somewhere else, add an entry, and return when they really don't.

The other case: On mobile, where space is at a premium and efficiency is critical, hiding corner case scenarios can be very helpful too. ;)

**Comment by Desertsnowman** [comment]
This was fixed in the last update.
